version: '3'

services:
  app-debug:
    image: 'quiz/platform'
    container_name: 'quiz-debug'
    working_dir: '/app'
    volumes:
      - './docker/php/php_debug.ini:/opt/bitnami/php/etc/php.ini'
      - './:/app'
    ports:
      - "9003:9003"
    networks:
      - quiz_network

networks:
  quiz_network:
    external: true
